In [1]:
import pandas as pd

print("Setup successful")

Setup successful

In [2]:
import pandas as pd

app = pd.read_csv("D:/unclean_home_credit_dataset/application_train.csv")
bureau = pd.read_csv("D:/unclean_home_credit_dataset/bureau.csv")
prev_app = pd.read_csv("D:/unclean_home_credit_dataset/previous_application.csv")
inst_pay = pd.read_csv("D:/unclean_home_credit_dataset/installments_payments.csv")
credit_card_bal = pd.read_csv("D:/unclean_home_credit_dataset/credit_card_balance.csv")
pos_cash_bal = pd.read_csv("D:/unclean_home_credit_dataset/POS_CASH_balance.csv")

In [4]:
app.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Columns: 122 entries, SK_ID_CURR to AMT_REQ_CREDIT_BUREAU_YEAR
dtypes: float64(65), int64(41), str(16)
memory usage: 286.2 MB

In [5]:
app.columns

Index(['SK_ID_CURR', 'TARGET', 'NAME_CONTRACT_TYPE', 'CODE_GENDER',
       'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN', 'AMT_INCOME_TOTAL',
       'AMT_CREDIT', 'AMT_ANNUITY',
       ...
       'FLAG_DOCUMENT_18', 'FLAG_DOCUMENT_19', 'FLAG_DOCUMENT_20',
       'FLAG_DOCUMENT_21', 'AMT_REQ_CREDIT_BUREAU_HOUR',
       'AMT_REQ_CREDIT_BUREAU_DAY', 'AMT_REQ_CREDIT_BUREAU_WEEK',
       'AMT_REQ_CREDIT_BUREAU_MON', 'AMT_REQ_CREDIT_BUREAU_QRT',
       'AMT_REQ_CREDIT_BUREAU_YEAR'],
      dtype='str', length=122)

In [6]:
important_columns = [
    'SK_ID_CURR',
    'TARGET',
    'NAME_CONTRACT_TYPE',
    'CODE_GENDER',
    'FLAG_OWN_CAR',
    'FLAG_OWN_REALTY',
    'CNT_CHILDREN',
    'AMT_INCOME_TOTAL',
    'AMT_CREDIT',
    'AMT_ANNUITY',
    'AMT_GOODS_PRICE',
    'NAME_INCOME_TYPE',
    'NAME_FAMILY_STATUS',
    'OCCUPATION_TYPE',
    'CNT_FAM_MEMBERS',
    'REGION_RATING_CLIENT'
]

In [7]:
app = app[important_columns]

In [125]:
app.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   NAME_CONTRACT_TYPE    307511 non-null  str
 3   CODE_GENDER           307511 non-null  str
 4   FLAG_OWN_CAR          307511 non-null  str
 5   FLAG_OWN_REALTY       307511 non-null  str
 6   CNT_CHILDREN          307511 non-null  int64
 7   AMT_INCOME_TOTAL      307511 non-null  float64
 8   AMT_CREDIT            307511 non-null  float64
 9   AMT_ANNUITY           307511 non-null  float64
 10  AMT_GOODS_PRICE       307511 non-null  float64
 11  NAME_INCOME_TYPE      307511 non-null  str
 12  NAME_FAMILY_STATUS    307511 non-null  str
 13  OCCUPATION_TYPE       307511 non-null  str
 14  CNT_FAM_MEMBERS       307511 non-null  float64
 15  REGION_RATING_CLIENT  307511 non-null  int64
dtypes: float64(5), int64(4), str(7)
memory usage: 37.5 MB

In [126]:
app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,Laborers,1.0,2
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,Core staff,2.0,1
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,Laborers,1.0,2
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,Laborers,2.0,2
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,Core staff,1.0,2

In [127]:
app['NAME_CONTRACT_TYPE'].value_counts()

NAME_CONTRACT_TYPE
Cash loans         278232
Revolving loans     29279
Name: count, dtype: int64

In [128]:
app['CODE_GENDER'].value_counts()

CODE_GENDER
F          202448
M          105059
Unknown         4
Name: count, dtype: int64

In [120]:
app['FLAG_OWN_CAR'].value_counts()

FLAG_OWN_CAR
N    202924
Y    104587
Name: count, dtype: int64

In [129]:
app['FLAG_OWN_REALTY'].value_counts()

FLAG_OWN_REALTY
Y    213312
N     94199
Name: count, dtype: int64

In [130]:
app['NAME_INCOME_TYPE'].value_counts()

NAME_INCOME_TYPE
Working                 158774
Commercial associate     71617
Pensioner                55362
State servant            21703
Unemployed                  22
Student                     18
Businessman                 10
Maternity leave              5
Name: count, dtype: int64

In [131]:
app['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 196432
Single / not married     45444
Civil marriage           29775
Separated                19770
Widow                    16088
Unknown                      2
Name: count, dtype: int64

In [132]:
app['OCCUPATION_TYPE'].value_counts()

OCCUPATION_TYPE
Unknown                  96391
Laborers                 55186
Sales staff              32102
Core staff               27570
Managers                 21371
Drivers                  18603
High skill tech staff    11380
Accountants               9813
Medicine staff            8537
Security staff            6721
Cooking staff             5946
Cleaning staff            4653
Private service staff     2652
Low-skill Laborers        2093
Waiters/barmen staff      1348
Secretaries               1305
Realty agents              751
HR staff                   563
IT staff                   526
Name: count, dtype: int64

In [118]:
app['CODE_GENDER'] = app['CODE_GENDER'].replace('XNA','Unknown')

In [133]:
app.isnull().sum()

SK_ID_CURR              0
TARGET                  0
NAME_CONTRACT_TYPE      0
CODE_GENDER             0
FLAG_OWN_CAR            0
FLAG_OWN_REALTY         0
CNT_CHILDREN            0
AMT_INCOME_TOTAL        0
AMT_CREDIT              0
AMT_ANNUITY             0
AMT_GOODS_PRICE         0
NAME_INCOME_TYPE        0
NAME_FAMILY_STATUS      0
OCCUPATION_TYPE         0
CNT_FAM_MEMBERS         0
REGION_RATING_CLIENT    0
dtype: int64

In [100]:
app['CODE_GENDER'].value_counts()

CODE_GENDER
F      202448
M      105059
XNA         4
Name: count, dtype: int64

In [15]:
app['OCCUPATION_TYPE'] = app['OCCUPATION_TYPE'].fillna('Unknown')

In [18]:
app['AMT_ANNUITY'] = app['AMT_ANNUITY'].fillna(app['AMT_ANNUITY'].median())
app['AMT_GOODS_PRICE'] = app['AMT_GOODS_PRICE'].fillna(app['AMT_GOODS_PRICE'].median())
app['CNT_FAM_MEMBERS'] = app['CNT_FAM_MEMBERS'].fillna(app['CNT_FAM_MEMBERS'].median())

In [65]:
app.duplicated().sum()

np.int64(0)

In [23]:
app['TARGET']

0         1
1         0
2         0
3         0
4         0
         ..
307506    0
307507    0
307508    0
307509    1
307510    0
Name: TARGET, Length: 307511, dtype: int64

In [134]:
bureau.info()

<class 'pandas.DataFrame'>
Index: 1708453 entries, 0 to 1716427
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   CREDIT_ACTIVE           str
 2   DAYS_CREDIT             int64
 3   AMT_CREDIT_SUM          float64
 4   AMT_CREDIT_SUM_DEBT     float64
 5   AMT_CREDIT_SUM_OVERDUE  float64
 6   CREDIT_TYPE             str
dtypes: float64(3), int64(2), str(2)
memory usage: 104.3 MB

In [29]:
bureau_cols = [
    'SK_ID_CURR',               # join key
    'CREDIT_ACTIVE',            # active/closed
    'DAYS_CREDIT',              # when loan taken
    'AMT_CREDIT_SUM',           # total credit
    'AMT_CREDIT_SUM_DEBT',      # remaining debt
    'AMT_CREDIT_SUM_OVERDUE',   # overdue amount
    'CREDIT_TYPE'    
]

In [30]:
bureau = bureau[bureau_cols]

In [81]:
bureau.info()

<class 'pandas.DataFrame'>
Index: 1708453 entries, 0 to 1716427
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   CREDIT_ACTIVE           str
 2   DAYS_CREDIT             int64
 3   AMT_CREDIT_SUM          float64
 4   AMT_CREDIT_SUM_DEBT     float64
 5   AMT_CREDIT_SUM_OVERDUE  float64
 6   CREDIT_TYPE             str
dtypes: float64(3), int64(2), str(2)
memory usage: 104.3 MB

In [139]:
bureau.head()

,SK_ID_CURR,CREDIT_ACTIVE,DAYS_CREDIT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE
0,215354,Closed,-497,91323.0,0.0,0.0,Consumer credit
1,215354,Active,-208,225000.0,171342.0,0.0,Credit card
2,215354,Active,-203,464323.5,0.0,0.0,Consumer credit
3,215354,Active,-203,90000.0,0.0,0.0,Credit card
4,215354,Active,-629,2700000.0,0.0,0.0,Consumer credit

In [136]:
bureau.isnull().sum()

SK_ID_CURR                0
CREDIT_ACTIVE             0
DAYS_CREDIT               0
AMT_CREDIT_SUM            0
AMT_CREDIT_SUM_DEBT       0
AMT_CREDIT_SUM_OVERDUE    0
CREDIT_TYPE               0
dtype: int64

In [140]:
bureau['CREDIT_ACTIVE'].value_counts()

CREDIT_ACTIVE
Closed      1074323
Active       627642
Sold           6467
Bad debt         21
Name: count, dtype: int64

In [138]:
bureau['CREDIT_TYPE'].value_counts()

CREDIT_TYPE
Consumer credit                                 1247478
Credit card                                      398726
Car loan                                          27496
Mortgage                                          18294
Microloan                                         12351
Loan for business development                      1966
Another type of loan                               1012
Unknown type of loan                                555
Loan for working capital replenishment              467
Cash loan (non-earmarked)                            56
Real estate loan                                     27
Loan for the purchase of equipment                   19
Loan for purchase of shares (margin lending)          4
Mobile operator loan                                  1
Interbank credit                                      1
Name: count, dtype: int64

In [34]:
bureau['AMT_CREDIT_SUM_DEBT'] = bureau['AMT_CREDIT_SUM_DEBT'].fillna(0)

In [35]:
bureau['AMT_CREDIT_SUM'] = bureau['AMT_CREDIT_SUM'].fillna(bureau['AMT_CREDIT_SUM'].median())

In [69]:
bureau.duplicated().sum()

np.int64(0)

In [39]:
bureau = bureau.drop_duplicates()

In [47]:
bureau_agg = bureau.groupby('SK_ID_CURR').agg({
    'AMT_CREDIT_SUM': 'sum',
    'AMT_CREDIT_SUM_DEBT': 'sum',
    'AMT_CREDIT_SUM_OVERDUE': 'sum',
    'CREDIT_ACTIVE': 'count'
}).reset_index()

In [48]:
bureau_agg.columns = [
    'SK_ID_CURR',
    'TOTAL_CREDIT',
    'TOTAL_DEBT',
    'TOTAL_OVERDUE',
    'TOTAL_LOANS'
]

In [57]:
bureau_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 305811 entries, 0 to 305810
Data columns (total 5 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   SK_ID_CURR     305811 non-null  int64
 1   TOTAL_CREDIT   305811 non-null  float64
 2   TOTAL_DEBT     305811 non-null  float64
 3   TOTAL_OVERDUE  305811 non-null  float64
 4   TOTAL_LOANS    305811 non-null  int64
dtypes: float64(3), int64(2)
memory usage: 11.7 MB

In [55]:
bureau_agg.head()

   SK_ID_CURR  TOTAL_CREDIT  TOTAL_DEBT  TOTAL_OVERDUE  TOTAL_LOANS
0      100001   1453365.000    596686.5            0.0            7
1      100002    865055.565    245781.0            0.0            8
2      100003   1017400.500         0.0            0.0            4
3      100004    189037.800         0.0            0.0            2
4      100005    657126.000    568408.5            0.0            3

In [51]:
bureau_agg.isnull().sum()

SK_ID_CURR       0
TOTAL_CREDIT     0
TOTAL_DEBT       0
TOTAL_OVERDUE    0
TOTAL_LOANS      0
dtype: int64

In [52]:
bureau_agg.duplicated().sum()

np.int64(0)

In [53]:
bureau_agg.describe()

          SK_ID_CURR  TOTAL_CREDIT    TOTAL_DEBT  TOTAL_OVERDUE    TOTAL_LOANS
count  305811.000000  3.058110e+05  3.058110e+05   3.058110e+05  305811.000000
mean   278047.300091  1.982543e+06  6.533393e+05   2.126316e+02       5.586630
std    102849.568343  4.017908e+06  1.636600e+06   1.568790e+04       4.403966
min    100001.000000  0.000000e+00 -6.981558e+06   0.000000e+00       1.000000
25%    188878.500000  3.464522e+05  0.000000e+00   0.000000e+00       2.000000
50%    277895.000000  9.758115e+05  1.732635e+05   0.000000e+00       4.000000
75%    367184.500000  2.338804e+06  6.763444e+05   0.000000e+00       8.000000
max    456255.000000  8.852079e+08  3.344983e+08   3.756681e+06     116.000000

In [54]:
final_agg = app.merge(bureau_agg, on='SK_ID_CURR', how='left')

In [58]:
final_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 20 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   NAME_CONTRACT_TYPE    307511 non-null  str
 3   CODE_GENDER           307511 non-null  str
 4   FLAG_OWN_CAR          307511 non-null  str
 5   FLAG_OWN_REALTY       307511 non-null  str
 6   CNT_CHILDREN          307511 non-null  int64
 7   AMT_INCOME_TOTAL      307511 non-null  float64
 8   AMT_CREDIT            307511 non-null  float64
 9   AMT_ANNUITY           307511 non-null  float64
 10  AMT_GOODS_PRICE       307511 non-null  float64
 11  NAME_INCOME_TYPE      307511 non-null  str
 12  NAME_FAMILY_STATUS    307511 non-null  str
 13  OCCUPATION_TYPE       307511 non-null  str
 14  CNT_FAM_MEMBERS       307511 non-null  float64
 15  REGION_RATING_CLIENT  307511 non-null  int64
 16  TOTAL_CREDIT          263491 non-null  float64
 17  TOTAL_DEBT            263491 non-null  float64
 18  TOTAL_OVERDUE         263491 non-null  float64
 19  TOTAL_LOANS           263491 non-null  float64
dtypes: float64(9), int64(4), str(7)
memory usage: 46.9 MB

In [61]:
final_agg.isnull().sum()

SK_ID_CURR              0
TARGET                  0
NAME_CONTRACT_TYPE      0
CODE_GENDER             0
FLAG_OWN_CAR            0
FLAG_OWN_REALTY         0
CNT_CHILDREN            0
AMT_INCOME_TOTAL        0
AMT_CREDIT              0
AMT_ANNUITY             0
AMT_GOODS_PRICE         0
NAME_INCOME_TYPE        0
NAME_FAMILY_STATUS      0
OCCUPATION_TYPE         0
CNT_FAM_MEMBERS         0
REGION_RATING_CLIENT    0
TOTAL_CREDIT            0
TOTAL_DEBT              0
TOTAL_OVERDUE           0
TOTAL_LOANS             0
dtype: int64

In [60]:
final_agg['TOTAL_CREDIT'] = final_agg['TOTAL_CREDIT'].fillna(0)
final_agg['TOTAL_DEBT'] = final_agg['TOTAL_DEBT'].fillna(0)
final_agg['TOTAL_OVERDUE'] = final_agg['TOTAL_OVERDUE'].fillna(0)
final_agg['TOTAL_LOANS'] = final_agg['TOTAL_LOANS'].fillna(0)

In [62]:
final_agg.duplicated().sum()

np.int64(0)

In [141]:
prev_app.info()

<class 'pandas.DataFrame'>
Index: 1589812 entries, 0 to 1670213
Data columns (total 11 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   SK_ID_CURR            1589812 non-null  int64
 1   NAME_CONTRACT_TYPE    1589812 non-null  str
 2   AMT_APPLICATION       1589812 non-null  float64
 3   AMT_CREDIT            1589812 non-null  float64
 4   AMT_ANNUITY           1589812 non-null  float64
 5   NAME_CONTRACT_STATUS  1589812 non-null  str
 6   NAME_PAYMENT_TYPE     1589812 non-null  str
 7   NAME_CLIENT_TYPE      1589812 non-null  str
 8   NAME_GOODS_CATEGORY   1589812 non-null  str
 9   CNT_PAYMENT           1589812 non-null  float64
 10  DAYS_DECISION         1589812 non-null  int64
dtypes: float64(4), int64(2), str(5)
memory usage: 145.6 MB

In [71]:
prev_col = [
    'SK_ID_CURR',                 # join key
    'NAME_CONTRACT_TYPE',         # loan type
    'AMT_APPLICATION',            # requested amount
    'AMT_CREDIT',                 # approved amount
    'AMT_ANNUITY',                # EMI
    'NAME_CONTRACT_STATUS',       # approved / refused
    'NAME_PAYMENT_TYPE',          # payment method
    'NAME_CLIENT_TYPE',           # new / repeat customer
    'NAME_GOODS_CATEGORY',        # goods type
    'CNT_PAYMENT',                # number of payments
    'DAYS_DECISION'               # when decision taken
]

In [72]:
prev_app = prev_app[prev_col]

In [82]:
prev_app.info()

<class 'pandas.DataFrame'>
Index: 1589812 entries, 0 to 1670213
Data columns (total 11 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   SK_ID_CURR            1589812 non-null  int64
 1   NAME_CONTRACT_TYPE    1589812 non-null  str
 2   AMT_APPLICATION       1589812 non-null  float64
 3   AMT_CREDIT            1589812 non-null  float64
 4   AMT_ANNUITY           1589812 non-null  float64
 5   NAME_CONTRACT_STATUS  1589812 non-null  str
 6   NAME_PAYMENT_TYPE     1589812 non-null  str
 7   NAME_CLIENT_TYPE      1589812 non-null  str
 8   NAME_GOODS_CATEGORY   1589812 non-null  str
 9   CNT_PAYMENT           1589812 non-null  float64
 10  DAYS_DECISION         1589812 non-null  int64
dtypes: float64(4), int64(2), str(5)
memory usage: 145.6 MB

In [142]:
prev_app.isnull().sum()

SK_ID_CURR              0
NAME_CONTRACT_TYPE      0
AMT_APPLICATION         0
AMT_CREDIT              0
AMT_ANNUITY             0
NAME_CONTRACT_STATUS    0
NAME_PAYMENT_TYPE       0
NAME_CLIENT_TYPE        0
NAME_GOODS_CATEGORY     0
CNT_PAYMENT             0
DAYS_DECISION           0
dtype: int64

In [144]:
prev_app.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,AMT_CREDIT,AMT_ANNUITY,NAME_CONTRACT_STATUS,NAME_PAYMENT_TYPE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,CNT_PAYMENT,DAYS_DECISION
0,271877,Consumer loans,17145.0,17145.0,1730.430,Approved,Cash through the bank,Repeater,Mobile,12.0,-73
1,108129,Cash loans,607500.0,679671.0,25188.615,Approved,Unknown,Repeater,Unknown,36.0,-164
2,122040,Cash loans,112500.0,136444.5,15060.735,Approved,Cash through the bank,Repeater,Unknown,12.0,-301
3,176158,Cash loans,450000.0,470790.0,47041.335,Approved,Cash through the bank,Repeater,Unknown,12.0,-512
4,202054,Cash loans,337500.0,404055.0,31924.395,Refused,Cash through the bank,Repeater,Unknown,24.0,-781

In [75]:
prev_app['AMT_ANNUITY'] = prev_app['AMT_ANNUITY'].fillna(prev_app['AMT_ANNUITY'].median())
prev_app['AMT_CREDIT'] = prev_app['AMT_CREDIT'].fillna(prev_app['AMT_CREDIT'].median())
prev_app['CNT_PAYMENT'] = prev_app['CNT_PAYMENT'].fillna(prev_app['CNT_PAYMENT'].median())

In [79]:
prev_app.duplicated().sum()

np.int64(0)

In [105]:
prev_app['NAME_CONTRACT_TYPE'].value_counts()

NAME_CONTRACT_TYPE
Consumer loans     724984
Cash loans         681707
Revolving loans    182793
Unknown               328
Name: count, dtype: int64

In [104]:
prev_app['NAME_CONTRACT_TYPE'] = prev_app['NAME_CONTRACT_TYPE'].replace('XNA','Unknown')

In [78]:
prev_app = prev_app.drop_duplicates()

In [85]:
prev_app['NAME_CONTRACT_TYPE'].isnull().sum()

np.int64(0)

In [91]:
prev_app['NAME_GOODS_CATEGORY'].value_counts()

NAME_GOODS_CATEGORY
Unknown                     874086
Mobile                      223475
Consumer Electronics        121078
Computers                   105009
Audio/Video                  98953
Furniture                    53456
Photo / Cinema Equipment     24913
Construction Materials       24862
Clothing and Accessories     23438
Auto Accessories              7366
Jewelry                       6259
Homewares                     5005
Medical Supplies              3833
Vehicles                      3358
Sport and Leisure             2974
Gardening                     2658
Other                         2547
Office Appliances             2324
Tourism                       1649
Medicine                      1544
Direct Sales                   442
Fitness                        209
Additional Service             128
Education                      107
Weapon                          77
Insurance                       60
Animals                          1
House Construction               1
Name: count, dtype: int64

In [90]:
prev_app['NAME_GOODS_CATEGORY'] = prev_app['NAME_GOODS_CATEGORY'].replace('XNA','Unknown')

In [108]:
prev_app['NAME_PAYMENT_TYPE'].value_counts()

NAME_PAYMENT_TYPE
Cash through the bank                        1026311
Unknown                                       554270
Non-cash from your account                      8159
Cashless from the account of the employer       1072
Name: count, dtype: int64

In [96]:
prev_app['NAME_PAYMENT_TYPE'] = prev_app['NAME_PAYMENT_TYPE'].replace('XNA','Unknown')

In [106]:
prev_app['NAME_CONTRACT_STATUS'].value_counts()

NAME_CONTRACT_STATUS
Approved        1034403
Refused          279215
Canceled         250377
Unused offer      25817
Name: count, dtype: int64

In [102]:
prev_app['NAME_CLIENT_TYPE'].value_counts()

NAME_CLIENT_TYPE
Repeater     1158150
New           299617
Refreshed     130286
Unknown         1759
Name: count, dtype: int64

In [101]:
prev_app['NAME_CLIENT_TYPE'] = prev_app['NAME_CLIENT_TYPE'].replace('XNA','Unknown')

In [149]:
inst_pay.info()

<class 'pandas.DataFrame'>
RangeIndex: 13605401 entries, 0 to 13605400
Data columns (total 6 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_CURR             int64
 1   NUM_INSTALMENT_NUMBER  int64
 2   DAYS_INSTALMENT        float64
 3   DAYS_ENTRY_PAYMENT     float64
 4   AMT_INSTALMENT         float64
 5   AMT_PAYMENT            float64
dtypes: float64(4), int64(2)
memory usage: 622.8 MB

In [154]:
inst_pay.isnull().sum()

SK_ID_CURR               0
NUM_INSTALMENT_NUMBER    0
DAYS_INSTALMENT          0
DAYS_ENTRY_PAYMENT       0
AMT_INSTALMENT           0
AMT_PAYMENT              0
dtype: int64

In [147]:
inst_col = [
    'SK_ID_CURR',          # join key
    'NUM_INSTALMENT_NUMBER',
    'DAYS_INSTALMENT',
    'DAYS_ENTRY_PAYMENT',
    'AMT_INSTALMENT',
    'AMT_PAYMENT'
]

In [148]:
inst_pay = inst_pay[inst_col]

In [158]:
inst_pay.head()

,SK_ID_CURR,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT,PAYMENT_DELAY,PAYMENT_DIFF
0,161674,6,-1180.0,-1187.0,6948.360,6948.360,-7.0,0.000
1,151639,34,-2156.0,-2156.0,1716.525,1716.525,0.0,0.000
2,193053,1,-63.0,-63.0,25425.000,25425.000,0.0,0.000
3,199697,3,-2418.0,-2426.0,24350.130,24350.130,-8.0,0.000
4,167756,2,-1383.0,-1366.0,2165.040,2160.585,17.0,-4.455

In [152]:
inst_pay['DAYS_ENTRY_PAYMENT'] = inst_pay['DAYS_ENTRY_PAYMENT'].fillna(0)
inst_pay['AMT_PAYMENT'] = inst_pay['AMT_PAYMENT'].fillna(0)

In [156]:
inst_pay['PAYMENT_DELAY'] = inst_pay['DAYS_ENTRY_PAYMENT'] - inst_pay['DAYS_INSTALMENT']

In [157]:
inst_pay['PAYMENT_DIFF'] = inst_pay['AMT_PAYMENT'] - inst_pay['AMT_INSTALMENT']

In [159]:
inst_agg = inst_pay.groupby('SK_ID_CURR').agg({
    'AMT_PAYMENT': 'sum',
    'AMT_INSTALMENT': 'sum',
    'PAYMENT_DELAY': 'mean'
}).reset_index()

In [161]:
inst_agg.columns = [
    'SK_ID_CURR',
    'TOTAL_PAYMENT',
    'TOTAL_INSTALMENT',
    'AVG_DELAY'
]

In [162]:
inst_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 339587 entries, 0 to 339586
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   SK_ID_CURR        339587 non-null  int64
 1   TOTAL_PAYMENT     339587 non-null  float64
 2   TOTAL_INSTALMENT  339587 non-null  float64
 3   AVG_DELAY         339587 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 10.4 MB

In [163]:
inst_agg.head()

   SK_ID_CURR  TOTAL_PAYMENT  TOTAL_INSTALMENT  AVG_DELAY
0      100001      41195.925         41195.925  -7.285714
1      100002     219625.695        219625.695 -20.421053
2      100003    1618864.650       1618864.650  -7.160000
3      100004      21288.465         21288.465  -7.666667
4      100005      56161.845         56161.845 -23.555556

In [165]:
inst_agg.isnull().sum()

SK_ID_CURR          0
TOTAL_PAYMENT       0
TOTAL_INSTALMENT    0
AVG_DELAY           0
dtype: int64

In [166]:
inst_agg.duplicated().sum()

np.int64(0)

In [170]:
credit_card_bal.info()

<class 'pandas.DataFrame'>
RangeIndex: 3840312 entries, 0 to 3840311
Data columns (total 5 columns):
 #   Column                     Dtype
---  ------                     -----
 0   SK_ID_CURR                 int64
 1   AMT_BALANCE                float64
 2   AMT_CREDIT_LIMIT_ACTUAL    int64
 3   AMT_PAYMENT_TOTAL_CURRENT  float64
 4   AMT_TOTAL_RECEIVABLE       float64
dtypes: float64(3), int64(2)
memory usage: 146.5 MB

In [168]:
cc_cols = [
    'SK_ID_CURR',
    'AMT_BALANCE',
    'AMT_CREDIT_LIMIT_ACTUAL',
    'AMT_PAYMENT_TOTAL_CURRENT',
    'AMT_TOTAL_RECEIVABLE'
]

In [169]:
credit_card_bal = credit_card_bal[cc_cols]

In [171]:
credit_card_bal.head()

,SK_ID_CURR,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_PAYMENT_TOTAL_CURRENT,AMT_TOTAL_RECEIVABLE
0,378907,56.970,135000,1800.0,0.000
1,363914,63975.555,45000,2250.0,64875.555
2,371185,31815.225,450000,2250.0,31460.085
3,337855,236572.110,225000,11925.0,233048.970
4,126868,453919.455,450000,27000.0,453919.455

In [172]:
credit_card_bal.isnull().sum()

SK_ID_CURR                   0
AMT_BALANCE                  0
AMT_CREDIT_LIMIT_ACTUAL      0
AMT_PAYMENT_TOTAL_CURRENT    0
AMT_TOTAL_RECEIVABLE         0
dtype: int64

In [173]:
cc_agg = credit_card_bal.groupby('SK_ID_CURR').agg({
    'AMT_BALANCE': 'mean',
    'AMT_CREDIT_LIMIT_ACTUAL': 'mean',
    'AMT_PAYMENT_TOTAL_CURRENT': 'sum',
    'AMT_TOTAL_RECEIVABLE': 'sum'
}).reset_index()

In [174]:
cc_agg.columns = [
    'SK_ID_CURR',
    'AVG_BALANCE',
    'AVG_CREDIT_LIMIT',
    'TOTAL_CC_PAYMENT',
    'TOTAL_RECEIVABLE'
]

In [175]:
cc_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 103558 entries, 0 to 103557
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   SK_ID_CURR        103558 non-null  int64
 1   AVG_BALANCE       103558 non-null  float64
 2   AVG_CREDIT_LIMIT  103558 non-null  float64
 3   TOTAL_CC_PAYMENT  103558 non-null  float64
 4   TOTAL_RECEIVABLE  103558 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 4.0 MB

In [176]:
cc_agg.isnull().sum()

SK_ID_CURR          0
AVG_BALANCE         0
AVG_CREDIT_LIMIT    0
TOTAL_CC_PAYMENT    0
TOTAL_RECEIVABLE    0
dtype: int64

In [177]:
cc_agg.head()

,SK_ID_CURR,AVG_BALANCE,AVG_CREDIT_LIMIT,TOTAL_CC_PAYMENT,TOTAL_RECEIVABLE
0,100006,0.000000,270000.000000,0.000,0.000
1,100011,54482.111149,164189.189189,334485.000,4028055.255
2,100013,18159.919219,131718.750000,654448.545,1737703.665
3,100021,0.000000,675000.000000,0.000,0.000
4,100023,0.000000,135000.000000,0.000,0.000

In [178]:
cc_agg.duplicated().sum()

np.int64(0)

In [179]:
pos_cash_bal.info()

<class 'pandas.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 8 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_PREV             int64
 1   SK_ID_CURR             int64
 2   MONTHS_BALANCE         int64
 3   CNT_INSTALMENT         float64
 4   CNT_INSTALMENT_FUTURE  float64
 5   NAME_CONTRACT_STATUS   str
 6   SK_DPD                 int64
 7   SK_DPD_DEF             int64
dtypes: float64(2), int64(5), str(1)
memory usage: 610.4 MB

In [180]:
pos_cols = [
    'SK_ID_CURR',
    'CNT_INSTALMENT',
    'CNT_INSTALMENT_FUTURE',
    'SK_DPD',
    'SK_DPD_DEF'
]

In [181]:
pos_cash_bal = pos_cash_bal[pos_cols]

In [191]:
pos_cash_bal.info()

<class 'pandas.DataFrame'>
RangeIndex: 10001358 entries, 0 to 10001357
Data columns (total 5 columns):
 #   Column                 Dtype
---  ------                 -----
 0   SK_ID_CURR             int64
 1   CNT_INSTALMENT         float64
 2   CNT_INSTALMENT_FUTURE  float64
 3   SK_DPD                 int64
 4   SK_DPD_DEF             int64
dtypes: float64(2), int64(3)
memory usage: 381.5 MB

In [196]:
pos_cash_bal.isnull().sum()

SK_ID_CURR               0
CNT_INSTALMENT           0
CNT_INSTALMENT_FUTURE    0
SK_DPD                   0
SK_DPD_DEF               0
dtype: int64

In [184]:
pos_cash_bal['CNT_INSTALMENT'] = pos_cash_bal['CNT_INSTALMENT'].fillna(0)
pos_cash_bal['CNT_INSTALMENT_FUTURE'] = pos_cash_bal['CNT_INSTALMENT_FUTURE'].fillna(0)

In [195]:
pos_cash_bal.duplicated().sum()

np.int64(0)

In [193]:
pos_cash_bal.duplicated().head()

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [194]:
pos_cash_bal = pos_cash_bal.drop_duplicates()

In [197]:
pos_cash_bal.head()

   SK_ID_CURR  CNT_INSTALMENT  CNT_INSTALMENT_FUTURE  SK_DPD  SK_DPD_DEF
0      182943            48.0                   45.0       0           0
1      367990            36.0                   35.0       0           0
2      397406            12.0                    9.0       0           0
3      269225            48.0                   42.0       0           0
4      334279            36.0                   35.0       0           0

In [198]:
pos_agg = pos_cash_bal.groupby('SK_ID_CURR').agg({
    'CNT_INSTALMENT': 'mean',
    'CNT_INSTALMENT_FUTURE': 'mean',
    'SK_DPD' : 'mean',
    'SK_DPD_DEF' : 'mean'
}).reset_index()

In [199]:
pos_agg.columns = [
    'SK_ID_CURR',
    'AVG_INSTALMENTS',
    'AVG_INSTALMENTS_FUTURE',
    'AVG_DPD',
    'AVG_DPD_DEF'
]

In [200]:
pos_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 337252 entries, 0 to 337251
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   SK_ID_CURR              337252 non-null  int64
 1   AVG_INSTALMENTS         337252 non-null  float64
 2   AVG_INSTALMENTS_FUTURE  337252 non-null  float64
 3   AVG_DPD                 337252 non-null  float64
 4   AVG_DPD_DEF             337252 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 12.9 MB

In [201]:
pos_agg.isnull().sum()

SK_ID_CURR                0
AVG_INSTALMENTS           0
AVG_INSTALMENTS_FUTURE    0
AVG_DPD                   0
AVG_DPD_DEF               0
dtype: int64

In [202]:
pos_agg.duplicated().sum()

np.int64(0)

In [203]:
pos_agg.head()

   SK_ID_CURR  AVG_INSTALMENTS  AVG_INSTALMENTS_FUTURE   AVG_DPD  AVG_DPD_DEF
0      100001         4.000000                1.833333  1.166667     1.166667
1      100002        24.000000               15.000000  0.000000     0.000000
2      100003         9.650000                4.950000  0.000000     0.000000
3      100004         3.750000                2.250000  0.000000     0.000000
4      100005        10.636364                6.545455  0.000000     0.000000

In [204]:
app.info()

<class 'pandas.DataFrame'>
RangeIndex: 307511 entries, 0 to 307510
Data columns (total 16 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   SK_ID_CURR            307511 non-null  int64
 1   TARGET                307511 non-null  int64
 2   NAME_CONTRACT_TYPE    307511 non-null  str
 3   CODE_GENDER           307511 non-null  str
 4   FLAG_OWN_CAR          307511 non-null  str
 5   FLAG_OWN_REALTY       307511 non-null  str
 6   CNT_CHILDREN          307511 non-null  int64
 7   AMT_INCOME_TOTAL      307511 non-null  float64
 8   AMT_CREDIT            307511 non-null  float64
 9   AMT_ANNUITY           307511 non-null  float64
 10  AMT_GOODS_PRICE       307511 non-null  float64
 11  NAME_INCOME_TYPE      307511 non-null  str
 12  NAME_FAMILY_STATUS    307511 non-null  str
 13  OCCUPATION_TYPE       307511 non-null  str
 14  CNT_FAM_MEMBERS       307511 non-null  float64
 15  REGION_RATING_CLIENT  307511 non-null  int64
dtypes: float64(5), int64(4), str(7)
memory usage: 37.5 MB

In [205]:
app.head()

,SK_ID_CURR,TARGET,NAME_CONTRACT_TYPE,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,AMT_CREDIT,AMT_ANNUITY,AMT_GOODS_PRICE,NAME_INCOME_TYPE,NAME_FAMILY_STATUS,OCCUPATION_TYPE,CNT_FAM_MEMBERS,REGION_RATING_CLIENT
0,100002,1,Cash loans,M,N,Y,0,202500.0,406597.5,24700.5,351000.0,Working,Single / not married,Laborers,1.0,2
1,100003,0,Cash loans,F,N,N,0,270000.0,1293502.5,35698.5,1129500.0,State servant,Married,Core staff,2.0,1
2,100004,0,Revolving loans,M,Y,Y,0,67500.0,135000.0,6750.0,135000.0,Working,Single / not married,Laborers,1.0,2
3,100006,0,Cash loans,F,N,Y,0,135000.0,312682.5,29686.5,297000.0,Working,Civil marriage,Laborers,2.0,2
4,100007,0,Cash loans,M,N,Y,0,121500.0,513000.0,21865.5,513000.0,Working,Single / not married,Core staff,1.0,2

In [206]:
bureau.info()

<class 'pandas.DataFrame'>
Index: 1708453 entries, 0 to 1716427
Data columns (total 7 columns):
 #   Column                  Dtype
---  ------                  -----
 0   SK_ID_CURR              int64
 1   CREDIT_ACTIVE           str
 2   DAYS_CREDIT             int64
 3   AMT_CREDIT_SUM          float64
 4   AMT_CREDIT_SUM_DEBT     float64
 5   AMT_CREDIT_SUM_OVERDUE  float64
 6   CREDIT_TYPE             str
dtypes: float64(3), int64(2), str(2)
memory usage: 104.3 MB

In [207]:
bureau.head()

,SK_ID_CURR,CREDIT_ACTIVE,DAYS_CREDIT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE
0,215354,Closed,-497,91323.0,0.0,0.0,Consumer credit
1,215354,Active,-208,225000.0,171342.0,0.0,Credit card
2,215354,Active,-203,464323.5,0.0,0.0,Consumer credit
3,215354,Active,-203,90000.0,0.0,0.0,Credit card
4,215354,Active,-629,2700000.0,0.0,0.0,Consumer credit

In [208]:
prev_app.info()

<class 'pandas.DataFrame'>
Index: 1589812 entries, 0 to 1670213
Data columns (total 11 columns):
 #   Column                Non-Null Count    Dtype
---  ------                --------------    -----
 0   SK_ID_CURR            1589812 non-null  int64
 1   NAME_CONTRACT_TYPE    1589812 non-null  str
 2   AMT_APPLICATION       1589812 non-null  float64
 3   AMT_CREDIT            1589812 non-null  float64
 4   AMT_ANNUITY           1589812 non-null  float64
 5   NAME_CONTRACT_STATUS  1589812 non-null  str
 6   NAME_PAYMENT_TYPE     1589812 non-null  str
 7   NAME_CLIENT_TYPE      1589812 non-null  str
 8   NAME_GOODS_CATEGORY   1589812 non-null  str
 9   CNT_PAYMENT           1589812 non-null  float64
 10  DAYS_DECISION         1589812 non-null  int64
dtypes: float64(4), int64(2), str(5)
memory usage: 145.6 MB

In [209]:
prev_app.head()

,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_APPLICATION,AMT_CREDIT,AMT_ANNUITY,NAME_CONTRACT_STATUS,NAME_PAYMENT_TYPE,NAME_CLIENT_TYPE,NAME_GOODS_CATEGORY,CNT_PAYMENT,DAYS_DECISION
0,271877,Consumer loans,17145.0,17145.0,1730.430,Approved,Cash through the bank,Repeater,Mobile,12.0,-73
1,108129,Cash loans,607500.0,679671.0,25188.615,Approved,Unknown,Repeater,Unknown,36.0,-164
2,122040,Cash loans,112500.0,136444.5,15060.735,Approved,Cash through the bank,Repeater,Unknown,12.0,-301
3,176158,Cash loans,450000.0,470790.0,47041.335,Approved,Cash through the bank,Repeater,Unknown,12.0,-512
4,202054,Cash loans,337500.0,404055.0,31924.395,Refused,Cash through the bank,Repeater,Unknown,24.0,-781

In [210]:
inst_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 339587 entries, 0 to 339586
Data columns (total 4 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   SK_ID_CURR        339587 non-null  int64
 1   TOTAL_PAYMENT     339587 non-null  float64
 2   TOTAL_INSTALMENT  339587 non-null  float64
 3   AVG_DELAY         339587 non-null  float64
dtypes: float64(3), int64(1)
memory usage: 10.4 MB

In [211]:
inst_agg.head()

   SK_ID_CURR  TOTAL_PAYMENT  TOTAL_INSTALMENT  AVG_DELAY
0      100001      41195.925         41195.925  -7.285714
1      100002     219625.695        219625.695 -20.421053
2      100003    1618864.650       1618864.650  -7.160000
3      100004      21288.465         21288.465  -7.666667
4      100005      56161.845         56161.845 -23.555556

In [212]:
cc_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 103558 entries, 0 to 103557
Data columns (total 5 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   SK_ID_CURR        103558 non-null  int64
 1   AVG_BALANCE       103558 non-null  float64
 2   AVG_CREDIT_LIMIT  103558 non-null  float64
 3   TOTAL_CC_PAYMENT  103558 non-null  float64
 4   TOTAL_RECEIVABLE  103558 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 4.0 MB

In [213]:
cc_agg.head()

,SK_ID_CURR,AVG_BALANCE,AVG_CREDIT_LIMIT,TOTAL_CC_PAYMENT,TOTAL_RECEIVABLE
0,100006,0.000000,270000.000000,0.000,0.000
1,100011,54482.111149,164189.189189,334485.000,4028055.255
2,100013,18159.919219,131718.750000,654448.545,1737703.665
3,100021,0.000000,675000.000000,0.000,0.000
4,100023,0.000000,135000.000000,0.000,0.000

In [214]:
pos_agg.info()

<class 'pandas.DataFrame'>
RangeIndex: 337252 entries, 0 to 337251
Data columns (total 5 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   SK_ID_CURR              337252 non-null  int64
 1   AVG_INSTALMENTS         337252 non-null  float64
 2   AVG_INSTALMENTS_FUTURE  337252 non-null  float64
 3   AVG_DPD                 337252 non-null  float64
 4   AVG_DPD_DEF             337252 non-null  float64
dtypes: float64(4), int64(1)
memory usage: 12.9 MB

In [215]:
pos_agg.head()

   SK_ID_CURR  AVG_INSTALMENTS  AVG_INSTALMENTS_FUTURE   AVG_DPD  AVG_DPD_DEF
0      100001         4.000000                1.833333  1.166667     1.166667
1      100002        24.000000               15.000000  0.000000     0.000000
2      100003         9.650000                4.950000  0.000000     0.000000
3      100004         3.750000                2.250000  0.000000     0.000000
4      100005        10.636364                6.545455  0.000000     0.000000

In [216]:
# Check duplicates in main table
app['SK_ID_CURR'].duplicated().sum()

np.int64(0)

In [218]:
len(set(app['SK_ID_CURR']) - set(cc_agg['SK_ID_CURR']))

220606

In [219]:
app.to_csv("application_train.csv",index=False)

In [220]:
bureau.to_csv("bureau.csv",index=False)

In [221]:
prev_app.to_csv("previous_application.csv",index=False)

In [222]:
inst_agg.to_csv("installment_summary.csv",index=False)

In [223]:
cc_agg.to_csv("credit_card_summary.csv",index=False)

In [224]:
pos_agg.to_csv("pos_cash_summary.csv",index=False)